### ISSUE TITLE
Z-Weather dosent report 

### ISSUE THREAD

**Issue by edorf83** [mruiter/com.popp#28]
Do not get all the values I should get at my Popp Z-Weather. 

What is the problem?

![z-weather](https://user-images.githubusercontent.com/43094467/45266718-ba94b200-b45f-11e8-96a7-86fb9fe02a1b.jpg)

**Comment by dicknystrand** [comment]
Hi

Is this issue fixed?

**Comment by Tigerliljan** [comment]
I have the same problem!

**Comment by urbanskil** [comment]
Still have this problem. How can i help?
Urban

**Comment by Tigerliljan** [comment]
Hello!
Yes I still have thisproblem, can only see this information

[cid:image001.jpg@01D4C065.AB8866A0]

Running v2.0.6

/Magnus
[signature_851109467]

Från: urbanskil <notifications@github.com>
Svara till: "mruiter/com.popp" <reply@reply.github.com>
Datum: fredag 8 februari 2019 08:57
Till: "mruiter/com.popp" <com.popp@noreply.github.com>
Kopia: Magnus Blondell <magnus@tigerliljan.se>, Comment <comment@noreply.github.com>
Ämne: Re: [mruiter/com.popp] Z-Weather dosent report (#28)


Still have this problem. How can i help?
Urban

**Comment by urbanskil** [comment]
[logzwave.txt](https://github.com/mruiter/com.popp/files/2849401/logzwave.txt)
Node[12] is the Z-weather device

**Comment by osochor** [comment]
Here the same Problem, Z-Weather doesn’t report wind speed, dewpoint and pressure.

**Comment by piveslat** [comment]
Would be great to see all sensor values. And have a flow event ’wind threshold triggered’ for the wind threshold set on the device. But i guess reading wind speed at all would be a good firat step 😉

**Comment by piveslat** [comment]
![image](https://user-images.githubusercontent.com/42740540/52886262-03ba0200-3174-11e9-82c8-f8e53a97edd8.png)

Z-weather resolved(!) Think I made it after cloning the repository and fault tracing by making my own app. Found an error with string comparisons for the "lost" values above. They were in the files from the sensor all the time but not interpeted correctly.
I have no experience in publishing any updated app versions to the homey app store but if I can get the developers attention he can hopefully make the necessary updates and help =)

ps. I have 0 wind at the moment because the device is lying on a chair on my balcony =) ds.

**Comment by urbanskil** [comment]
Hi! 
Great work. I have no experience working with Git but I think you have to make a pull request and publish your code.
/Urban

**Comment by piveslat** [comment]
Did some additional cleanup.
- Dew point now reported in unit °C
- Barometric Pressure unit in kPa since this is what is reported from the sensor. Not mbar as stated in the spec.

I will have to validate the flow cards before attempting to push anything to github. The meter values for Wind speed, dew point and pressure aren´t coming up as flow cards yet.....

![image](https://user-images.githubusercontent.com/42740540/52897044-e581ef80-31cf-11e9-92f1-a690ef71b99c.png)

**Comment by mruiter** [comment]
Im almost back from being away from the country . If you can send in the changed code i can add iT or you could indeed also create a Pull request .

I Will also give the popp smoke alert Some looks because iT doesnt seem to work under V2

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
And great work btw

Verstuurd vanaf mijn iPhone

**Comment by piveslat** [comment]
Hi Marco,

Can you contact me by e-Mail to get some feedback on the z-weather issues?

Thanks

Med vänlig hälsning,
Per Iveslätt
Managing partner
T +46761739840
per.iveslatt@mindqore.se<mailto:per.iveslatt@mindqore.se>

MindQore AB
www.mindqore.se<http://www.mindqore.se/>
Registration No. 556945-8853

16 feb. 2019 kl. 11:11 skrev Marco Ruiter <notifications@github.com<mailto:notifications@github.com>>:

And great work btw

Verstuurd vanaf mijn iPhone

**Comment by dicknystrand** [comment]
Hi, when do you plan to anounce the uppdate? Is it possible to download the working fork?

**Comment by JackDaniel007** [comment]
Is there still hope that the error will be corrected?

**Comment by osochor** [comment]
Dear @piveslat do you already provide the code to @mruiter?
THX

**Comment by maheldt** [comment]
Hello guys, any news on the update regarding z-weather reporting?.... 
br
MH 
Norway

**Comment by Tigerliljan** [comment]
Any update??

**Comment by mapulu** [comment]
It is solved

**Comment by mruiter** [comment]
Confirmed working in latest versions of app
