### ISSUE TITLE
Request Popp Keypad

### ISSUE THREAD

**Issue by danho90** [mruiter/com.popp#65]
Hello,
I have a problem with my Popp keypad but I don't know if the problem comes from the keypad or the integration with Homey.
When I put codes on the keypad, HOMEY does not always receive the codes. No indication or sometimes it takes almost 30 seconds before the status changes. Do you have any idea where the problem might come from?
The keypad is nearly of the box.
Thank you in advance and best regards
Dany

**Comment by mruiter** [comment]
This is probably the zwave core issues that are present in Homey .
The keypad uses a protocol Flirs that’s a native zwave way of communicating and doesn’t drain the battery since.

Athom aka Emile said he is not willing to incorporate the zwave standard into homey because he doesn’t like it . Aka it doesn’t work well because of all the patchwork they have in the zwave homeyos and they don’t have time or are willing to clean the shit.

So please report to athom at support@athom.com that you’re keypad is missing communication and is working bad because it uses flirs and homey doesn’t support it.

If support mails you back homey does then mail them back that they should ask there supervisors because homey doesn’t 

Until support is made you’re keypad will be slow and also missing some reports 

Verstuurd vanaf mijn iPhone
